custom_ui/demo/parcel/urls.py
from django.conf.urls import url, include
from viewflow.flow.viewset import FlowViewSet
from .flows import DeliveryFlow


delivery_urls = FlowViewSet(DeliveryFlow).urls

app_name = 'parcel'
urlpatterns = [
     url(r'^delivery/', include((delivery_urls, 'delivery')))
]

custom_ui/demo/urls.py
from django.views import generic
from django.conf.urls import url, include


urlpatterns = [
    url('^$', generic.TemplateView.as_view(template_name='index.html')),
    url('^parcel/', include('demo.parcel.urls')),
    url('^accounts/', include('django.contrib.auth.urls')),
]

custom_ui/demo/parcel/models.py
from django.db import models
from viewflow.models import Process


class DeliveryProcess(Process):
    planet = models.CharField(max_length=250)
    description = models.TextField()
    approved = models.BooleanField(default=False)
    approved_at = models.DateTimeField(null=True)
    drop_status = models.CharField(
        null=True, max_length=3, default=None,
        choices=(('SCF', 'Successful'),
                 ('ERR', 'Unsuccessful'))
    )
    delivery_report = models.TextField(null=True)

custom_ui/demo/parcel/forms.py
from django import forms
from django.utils import timezone

from .models import DeliveryProcess


class ApproveForm(forms.ModelForm):
    def save(self, commit=True):
        instance = super(ApproveForm, self).save(commit=False)
        instance.approved_at = timezone.now()
        if commit:
            instance.save()
        return instance

    class Meta:
        model = DeliveryProcess
        fields = ['approved']


class DropStatusForm(forms.ModelForm):
    class Meta:
        model = DeliveryProcess
        fields = ['drop_status']
        widgets = {
            'drop_status': forms.RadioSelect
        }

custom_ui/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Viewflow - Reusable Workflow Library</title>
    <link href="{% static 'custom.css' %}" rel="stylesheet">
    {% include 'material/includes/material_css.html' %}
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li {% block nav_home_cls%}{% endblock %}>
            <a href="/"><i class="material-icons">home</i></a>
          </li>
          {% if user.is_authenticated %}
          <li {% block nav_parcels_cls %}{% endblock %}>
            <a href="{% url 'parcel:delivery:index' %}"><i class="material-icons left">mail_outline</i>Parcels</a>
          </li>
          <li {% block nav_queue_cls %}{% endblock %}>
            <a href="{% url 'parcel:delivery:queue' %}">
              <i class="material-icons left">assignment</i>Queue
              {% if queue_count %}<sup class="red" style="padding:0 5px 0 5px">{{ queue_count }}</sup>{% endif %}
            </a>
          </li>
          <li {% block nav_tasks_cls %}{% endblock %}>
            <a href="{% url 'parcel:delivery:tasks' %}">
              <i class="material-icons left">assignment_late</i>Tasks
              {% if inbox_count %}<sup class="red" style="padding:0 5px 0 5px">{{ inbox_count }}</sup>{% endif %}
            </a>
          </li>
          {% endif %}
        </ul>
        <ul class="right">
            <li {% block nav_login_cls%}{% endblock %}>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a href="{% url 'login' %}">Login</a>
                {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    <main class="container">
      {% block content %}{% endblock %}
    </main>
    {% if user.is_authenticated and perms.parcel.add_parcel %}
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'parcel:delivery:start' %}"><i class="material-icons">add</i></a>
    </div>
    {% endif %}

    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
  </body>
</html>

custom_ui/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block nav_home_cls%}class="active"{% endblock %}

{% block content %}
<div class="center">
  <img src="{% static 'lila.jpg' %}" class="responsive-img" style="max-height:500px" title="(c) http://futurama-madhouse.net/"/>
  <h4>Planet Express, Inc. Intergalactic Delivery</h4>
  <h5>The Viewflow <a href="http://viewflow.io" target="_blank">Cookbook</a> Sample.</h5>
</div>
{% endblock %}

custom_ui/templates/parcel/delivery/process_data.html
<div class="input-field">
  <i class="material-icons prefix">all_out</i>
  <input type="text" readonly value="{{ process.planet }}">
  <label class="active">Planet</label>
</div>
<div class="input-field">
  <i class="material-icons prefix">create</i>
  <textarea class="materialize-textarea" readonly>{{ process.description }}</textarea>
  <label class="active">Description</label>
</div>
<div style="padding-left:3em">
  <label>Approved<br/><br/></label>
  <div class="switch">
    <label>
      No
      <input type="checkbox" disabled="disabled" {% if process.approved %}checked{% endif %}>
      <span class="lever"></span>
      Yes
    </label><br/><br/>
  </div>
</div>
{% if process.drop_status %}
<div class="input-field">
  <i class="material-icons prefix">file_download</i>
  <input type="text" readonly value="{{ process.get_drop_status_display }}">
  <label class="active">Drop Status</label>
</div>
{% if process.delivery_report %}
<div class="input-field">
  <i class="material-icons prefix">assignment_finished</i>
  <textarea class="materialize-textarea" readonly>{{ process.delivery_report }}</textarea>
  <label class="active">Delivery Report</label>
</div>
{% endif %}
{% endif %}

custom_ui/templates/parcel/delivery/process_detail.html
{% extends 'base.html' %}
{% load viewflow %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">Parcel #{{ process.pk }}</h2>
<div class="row">
  <div class="col s12 m6 l5 offset-m3 offset-l2">
    <table>
      <thead>
        <tr>
          <td>#</td>
          <td>Description</td>
          <td>Owner</td>
          <td>Status</td>
        </tr>
      </thead>
      <tbody>
        {% for task in task_list %}
        {% flowurl task user=request.user as task_url %}
        <tr>
          <td>
            {% if task_url %}<a href="{{ task_url}}">{{ task.pk }}</a>{% else %}{{ task.pk }}{% endif %}
          </td>
          <td>{{ task.summary|default:task.flow_task }}</td>
          <td>{{ task.owner }}</td>
          <td>{{ task.status }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col s12 m6 l4 offset-m3 offset-l1">
    {% include_process_data process %}
  </div>
</div>
{% endblock %}

custom_ui/templates/parcel/delivery/process_list.html
{% extends 'base.html' %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">{{ view.flow_class }}</h2>
<div class="row">
  <div class="col s12 m12 l8 offset-l2">
    <table id="table" class="table bordered">
      <thead>
        <td>#</td>
        <td>Sent</td>
        <td>Planet</td>
        <td>Approved</td>
        <td>Status</td>
      </thead>
      <tbody>
        {% for process in process_list %}
        <tr>
          <td>
            <a href="{% url 'parcel:delivery:detail' process.pk %}">{{ process.pk }}</a>                        
          </td>
          <td>{{ process.created }}</td>
          <td>{{ process.planet }}</td>
          <td>{{ process.approved|yesno:"Yes,No" }}</td>
          <td>
            {% if process.finished %}
            {{ process.get_drop_status_display }}
            {% else %}
            {{ process.status }}
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

custom_ui/templates/parcel/delivery/queue.html
{% extends 'base.html' %}
{% load viewflow %}

{% block nav_queue_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">{{ view.flow_class }}</h2>
<div class="row">
  <div class="col s12 m12 l8 offset-l2">
    <table id="table" class="table bordered">
      <thead>
        <td>#</td>
        <td>Created</td>
        <td>Description</td>
        <td>Planet</td>
      </thead>
      <tbody>
        {% for task in queue %}
        {% flowurl task user=request.user as task_url %}
        <tr>
          <td>
            {% if task_url %}<a href="{{ task_url }}">{{ task.process.pk }}/{{ task.pk }}</a>{% else %}{{ task.process.pk }}/{{ task.pk }}{% endif %}
          </td>
          <td>{{ task.created }}</td>
          <td>{{ task.summary|default:task.flow_task }}</td>
          <td>{{ task.flow_process.planet }}</td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="4">No tasks in queue</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

custom_ui/templates/parcel/delivery/start.html
{% extends 'base.html' %}
{% load material_form %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">{{ activation.flow_task.task_title }}</h2>
<div class="row">
    <div class="col s12 m6 l4 offset-m3 offset-l4">
        <form method="POST">
            {% csrf_token %}
            {% form form=form %} {% endform %}
            {{ activation.management_form }}
            <div class="right">
                <button type="submit" name="_start" class="btn">Start</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

custom_ui/templates/parcel/delivery/task.html
{% extends 'base.html' %}
{% load material_form viewflow %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">
  <a href="{% url 'parcel:delivery:detail' activation.process.pk %}">Parcel #{{ activation.process.pk }}</a> &rang; {{ activation.flow_task }}
</h2>
<form method="POST">
  {% csrf_token %}
  <div class="row">
    <div class="col s12 m6 l6 offset-m3 offset-l2">
      {% form form=form %} {% endform %}
      {{ activation.management_form }}
      <div class="right">
      </div>
    </div>
    <div class="col s12 m6 l4 offset-m3">
      {% include_process_data activation.process %}
    </div>
  </div>
  <div class="row">
    <div class="col s12 m6 l10 offset-m3 offset-l2">
      <button type="submit" name="_start" class="btn">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

custom_ui/templates/parcel/delivery/task_assign.html
{% extends 'parcel/delivery/task_base.html' %}

{% block task_actions %}
<form method="POST">
  {% csrf_token %}
  <button type="submit" name="_assign" class="btn">Assign</button>
</form>
{% endblock %}

custom_ui/templates/parcel/delivery/task_base.html
{% extends 'base.html' %}
{% load viewflow %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">
  <a href="{% url 'parcel:delivery:detail' activation.process.pk %}">Parcel #{{ activation.process.pk }}</a> &rang; {{ activation.flow_task }}
</h2>
<div class="row">
  <div class="col s12 m6 l6 offset-m3 offset-l2">
    <ul class="collection">
      {% if activation.task.owner %}
      <li class="collection-item avatar">
        <i class="material-icons circle">person</i>
        <span class="title">Assignee</span>
        <p>{{ activation.task.owner }}</p>
      </li>
      {% endif %}
      {% if activation.task.created and not activation.task.started %}
      <li class="collection-item avatar">
        <i class="material-icons circle">alarm_add</i>
        <span class="title">Created</span>
        <p>{{ activation.task.created }}</p>
      </li>
      {% endif %}
      {% if activation.task.started %}
      <li class="collection-item avatar">
        <i class="material-icons circle">alarm_add</i>
        <span class="title">Started</span>
        <p>{{ activation.task.started }}</p>
      </li>
      {% endif %}
      {% if activation.task.finished %}
      <li class="collection-item avatar">
        <i class="material-icons circle">done_all</i>
        <span class="title">Finished</span>
        <p>{{ activation.task.finished }}</p>
      </li>
      {% endif %}
    </ul>
  </div>
  <div class="col s12 m6 l4 offset-m3">
    {% include_process_data activation.process %}
  </div>
</div>
<div class="row">
  <div class="col s12 m6 l10 offset-m3 offset-l2">
    {% block task_actions %}{% endblock %}
  </div>
</div>
{% endblock %}

custom_ui/templates/parcel/delivery/task_detail.html
{% extends 'parcel/delivery/task_base.html' %}
{% load viewflow %}

{% block nav_parcels_cls %}class="active"{% endblock %}

{% block task_actions %}
{% flowurl activation.task 'execute' user=request.user as execute_url %}
{% if execute_url %}
<a href="{{ execute_url }}" class="btn primary">Execute</a>
{% endif %}
{% flowurl activation.task 'assign' user=request.user as assign_url %}
{% if assign_url %}
<a href="{{ assign_url }}" class="btn blue">Assign</a>
{% endif %}

{% flowurl activation.task 'unassign' user=request.user as unassign_url %}
{% if unassign_url %}
<a href="{{ unassign_url }}" class="btn blue">Unassign</a>
{% endif %}
{% endblock %}

custom_ui/templates/parcel/delivery/task_list.html
{% extends 'base.html' %}
{% load viewflow %}

{% block nav_tasks_cls %}class="active"{% endblock %}

{% block content %}
<h2 class="center">{{ view.flow_class }}</h2>
<div class="row">
  <div class="col s12 m12 l8 offset-l2">
    <table id="table" class="table bordered">
      <thead>
        <td>#</td>
        <td>Created</td>
        <td>Description</td>
        <td>Planet</td>
      </thead>
      <tbody>
        {% for task in task_list %}
        {% flowurl task user=request.user as task_url %}
        <tr>
          <td>
            {% if task_url %}<a href="{{ task_url }}">{{ task.process.pk }}/{{ task.pk }}</a>{% else %}{{ task.process.pk }}/{{ task.pk }}{% endif %}
          </td>
          <td>{{ task.created }}</td>
          <td>{{ task.summary|default:task.flow_task }}</td>
          <td>{{ task.flow_process.planet }}</td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="4">No tasks assigned</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

custom_ui/templates/parcel/delivery/task_unassign.html
{% extends 'parcel/delivery/task_base.html' %}

{% block task_actions %}
<form method="POST">
  {% csrf_token %}
  <button type="submit" name="run_action" class="btn">Unassign</button>
</form>
{% endblock %}